name = "bennyhartnett-router"
main = "workers/router.js"
compatibility_date = "2025-12-01"

routes = [
  { pattern = "bennyhartnett.com/*", zone_name = "bennyhartnett.com" },
  { pattern = "*.bennyhartnett.com/*", zone_name = "bennyhartnett.com" }
]
